### ISSUE TITLE
Some FAQs.

### ISSUE THREAD

**Issue by KAGEYAM4** [TRIAEIOU/flexible-cloze-2#1]
I have some question , would you please answer them and maybe add them to FAQs.

1. Why Totally different addon , is the `Enhanced clozed` deprecated ?
2. Did you made this addon as `Enhanced clozed` was dead and wanted to incorporate the new anki features ?
3. Can i migrate all my `Enhaced clozed` notes to `Flexible Cloze` ? ( select all notes made in `enhanced cloze ` and mass migrate to `flixible cloze` , maybe i will trial and error this.

**Comment by triaeiou** [comment]
Hi,

> Why Totally different addon , is the Enhanced clozed deprecated ?
> Did you made this addon as Enhanced clozed was dead and wanted to incorporate the new anki features ?

[Enhanced Cloze](https://ankiweb.net/shared/info/1990296174) is a completely different addon by another author ([RisingOrange]( https://github.com/RisingOrange)). I was originally inspired by `Enhanced Cloze` and `Cloze (HideAll)` when I created `Flexible cloze` but wanted some different functionality and possibly a cleaner approach for card generation. I have no idea as to the development status of `Enhanced Cloze`, you will need to check with RisingOrange for that.

> Can i migrate all my Enhaced clozed notes to Flexible Cloze ? ( select all notes made in enhanced cloze  and mass migrate to flixible cloze , maybe i will trial and error this.
You should be able to just change the note type (unless `Enhanced Cloze` does something funky behind the scenes).

**Comment by KAGEYAM4** [comment]
Thanks for the Information.
