### ISSUE TITLE
Make `Title filed` optional.

### ISSUE THREAD

**Issue by KAGEYAM4** [TRIAEIOU/flexible-cloze-2#2]
How to make Title Field optinal. Sometimes i don't want to use Title filed, but then i get a warning `first field is empty`

**Comment by triaeiou** [comment]
Anki requires the first field to contain data, either:
- Make the `Text` field the first field: from the Anki main window: `Tools` → `Manage Note Types` → `Flexible cloze 2` → `Fields` → Select `Text` field → `Reorder` and set to `1`. The cards will still look the same but in the `Add` and `Browser` windows the `Text` field will now come before the `Title` field.
- Set the first field to `.` (or something else) and select `Toggle sticky` to have Anki autofill the `Title` field.

**Comment by KAGEYAM4** [comment]
ok thank you. 

This is what i am trying to achive. Have the title field as optional and when reviewing the title field to show up only on the back card. 

For now i will look into it myself. Thank you.
