### ISSUE TITLE
Error : `Failed to parse styling template`

### ISSUE THREAD

**Issue by KAGEYAM4** [TRIAEIOU/flexible-cloze-2#3]
![image](https://user-images.githubusercontent.com/75798544/213952191-8afe6f68-f32e-4181-9c2e-e7ab24b404ed.png)

**Comment by triaeiou** [comment]
Thanks, when did you get this dialog? When you first installed the addon? It should only run when the addon is first installed (and then there shouldn't be an old template to parse) or on addon update (and I haven't published any updates). At any rate, to restore manually:

1. From the Anki main window: `Tools` → `Add-ons` → `Flexible cloze 2` → `View Files` will show the templates (`fc2-front.html`, `fc2-back.html` and `fc2.css`).
2. From the Anki main window: `Tools` → `Mange Note Types` → `Flexible cloze 2` → `Cards` and insert the contents of the files from step 1 manually in the `Card Types` dialog.

**Comment by KAGEYAM4** [comment]
I got this message on the first run , but as it said welcome message , i read it on the fly.

Was i suppose to do this after installing this ?


Then later after every restart of Anki , i got this message. Then i read it carefully and reported the issue as i was confuse on how to proceed.

**Comment by KAGEYAM4** [comment]
Edit disregard the last comment. 

I did a Test, removed addon and deleted the `flexible cloze note` and then reinstalled it , then restarted Anki. I didn't get the error `failed to parse...` only got the first bullet point in the screenshot.
Then i restarted , and then i received the `parse error`. 
Also i am confuse about what to do with `fc2-front.html`, `fc2-back.html` because the content of them seems to be mostly empty.
Take a look at the screenshot.
![image](https://user-images.githubusercontent.com/75798544/214129370-9ce1f5b3-4e18-4ff8-8b97-3950da695898.png)

Infact , the `fc2-back.html.bak` and `fc2-front.html.bak` seems to contain more info.

Here's default `flexible cloze note settings`
![image](https://user-images.githubusercontent.com/75798544/214129766-a3361e24-9313-4000-8ad7-952df8b87229.png)
![image](https://user-images.githubusercontent.com/75798544/214129787-d72b235a-6d1f-4b44-8d4d-b502c5b0cb07.png)
![image](https://user-images.githubusercontent.com/75798544/214129807-9beabc19-7ebf-4342-b02f-f6e4e931f29a.png)

**Comment by triaeiou** [comment]
Thanks, I looked at the update code and found two bugs, just uploaded an update, please try that one. With regards to the files in the addon folder: the update logic copies the current version of the templates from inside Anki and writes them to the `*.bak` filse and then copies the content from `fc2-front/back/css` into Anki.

**Comment by KAGEYAM4** [comment]
> Thanks, I looked at the update code and found two bugs, just uploaded an update, please try that one. With regards to the files in the addon folder: the update logic copies the current version of the templates from inside Anki and writes them to the `*.bak` files and then copies the content from `fc2-front/back/css` into Anki.

Thank you its working now.
