### ISSUE TITLE
The 'chars' remain visible during review.

### ISSUE THREAD

**Issue by hoonlight** [TRIAEIOU/flexible-cloze-2#4]
Hello, I am using anki 2.1.57 (6b7d372c) version on my m1 macbook, and no other addons are installed other than this addon.

I added the following cards. Field settings and other things are the same as FC2 defaults without any modification.

<img width="394" alt="2023-02-07 8 04 29" src="https://user-images.githubusercontent.com/98728125/217229232-1f3c9ff5-0564-4ee3-b469-6e57ded875df.png">

During review, the card displays '!'

<img width="302" alt="스크린샷 2023-02-07 오후 8 04 43" src="https://user-images.githubusercontent.com/98728125/217229269-3aec0a5b-e63d-494a-82b8-035dfc8d37fc.png">

If this is not intended, there seems to be a bug.

**Comment by triaeiou** [comment]
Thanks, you are correct, that's not the intent, should be fixed in 1.1.0 release from ankiweb, please check if it works for you.

**Comment by hoonlight** [comment]
thank you, It works
