### ISSUE TITLE
error Uncaught TypeError

### ISSUE THREAD

**Issue by hoonlight** [TRIAEIOU/flexible-cloze-2#7]
After adding a card to the deck and starting a review, the error below is displayed. 
This only happens when I start the review on the 'first' card(front side). It doesn't happen after that.

```
error Uncaught TypeError: Cannot read properties of null (reading 'style'):
TypeError: Cannot read properties of null (reading 'style')
    at nc (http://127.0.0.1:52990/_anki/js/reviewer.js:7:113091)
```

<img width="543" alt="screenshot" src="https://user-images.githubusercontent.com/98728125/236180713-3ece42aa-7406-4032-a134-3fd53e13c13f.png">

**Comment by triaeiou** [comment]
Thanks! Could you set `log: true` in the config (right now it should say `log: 'error'`) on the front/question as well as the back/answer side (depending on the reviewer win vs mac vs android vs iOS variables survive between the front and back)? That should print all function calls so I can get some more details on where this is happening. As a side note, you can set `log: false` to prevent any logging info, i set the default to `'error'` to encourage people to report problems.

**Comment by hoonlight** [comment]
Sure, This is the output when log:ture.

```
searcher. constructor ()
generate_expose
hide
scroll to
    line_height
    line height
    scrolling context to: -261.5
error Uncaught TypeError: Cannot read properties of null (reading 'style'):
TypeError: Cannot read properties of null (reading 'style')
    at nc (http://127.0.0.1:52990/_anki/js/reviewer.js:7:113091)
```

**Comment by triaeiou** [comment]
Thanks, I am not certain that error stems from FC2 (the "scrolling context to: xyz" should be pretty much the last thing that FC2 does until user interaction; also I don't get any such errors when I try different platforms). Could you try inserting one of the following into the template front: [fc2-front.html](https://gist.github.com/TRIAEIOU/404c8a23388abab434fc801e25c83f2c) or [fc2m-front.html](https://gist.github.com/TRIAEIOU/f9e04b640c46dd3bdc8d5ecc30bb4667) depending on if you use the "full"/5-field version or the "minimal"/2-field version? Please note that inserting it will overwrite any configuration changes you have done so please save those somewhere first. The only thing added in these gists is a log entry as the very last FC2 command on load to see if the error happens after or inside the FC2 code. 

If you could also check with [AnkiWebViewInspector](https://ankiweb.net/shared/info/31746032) console if you get the same error when using Ankis "normal" cloze note type?

**Comment by hoonlight** [comment]
> Thanks, I am not certain that error stems from FC2 (the "scrolling context to: xyz" should be pretty much the last thing that FC2 does until user interaction; also I don't get any such errors when I try different platforms). Could you try inserting one of the following into the template front: [fc2-front.html](https://gist.github.com/TRIAEIOU/404c8a23388abab434fc801e25c83f2c) or [fc2m-front.html](https://gist.github.com/TRIAEIOU/f9e04b640c46dd3bdc8d5ecc30bb4667) depending on if you use the "full"/5-field version or the "minimal"/2-field version? Please note that inserting it will overwrite any configuration changes you have done so please save those somewhere first. The only thing added in these gists is a log entry as the very last FC2 command on load to see if the error happens after or inside the FC2 code.
> 
> If you could also check with [AnkiWebViewInspector](https://ankiweb.net/shared/info/31746032) console if you get the same error when using Ankis "normal" cloze note type?

Thank you for your response. I tried inserting the [fc2m-front.html](https://gist.github.com/TRIAEIOU/f9e04b640c46dd3bdc8d5ecc30bb4667) and tested it again, but I encountered the same error message. However, I did not experience any issues with the basic cloze note type. Additionally, I am not using any other add-ons besides fc2.

This error only occurs once when starting the review, and it doesn't happen again afterward. As a result, I suspect that it might be related to the note initialization process.

<img width="299" alt="screenshot2" src="https://user-images.githubusercontent.com/98728125/236368864-26e2e9fc-2f72-4256-8f85-ef1ba3eb909e.png">

This is my AnkiWebViewInspector console. I'm not sure if this information is helpful to you, but I'm attaching it anyway.

As you pointed out, this error does not appear to impact the functionality of the add-on. Despite the error being displayed, the cloze still shows up correctly. I am currently using macOS, but I will soon test whether this error also occurs on Windows.

**Comment by triaeiou** [comment]
Thanks, with the gist, did the error log print `FC2 finished` before the error (i.e. between `scrolling context to: xyz`)?

With regards to the regular cloze; the red error log at the bottom of the card is specific to FC2 - did you check the `Console` of the AnkiWebViewInspector for any errors or warnings when reviewing a regular cloze note (you could also run Anki from command line and check what is written)?
![console](https://user-images.githubusercontent.com/94647023/236388384-f99f19e2-b3dd-41c3-9558-74bc24c33997.png)

Thanks!

**Comment by hoonlight** [comment]
You were right
This doesn't seem to be an fc2 issue. As a result of checking with AnkiWebViewInspector, the same error message occurred in the default cloze note.



<img width="301" alt="console" src="https://user-images.githubusercontent.com/98728125/236601108-08f1c78a-60eb-4014-8b06-fcd2a2d0e930.png">


<img width="299" alt="issues" src="https://user-images.githubusercontent.com/98728125/236601110-3971ade4-e151-4646-a138-98aa7000c049.png">


Thanks for helping me figure out the problem. I will report to Anki instead of FC2.

**Comment by triaeiou** [comment]
No problem, try disabling all addons once to see if there is an addon that is causing the error in the Anki reviewer. As for FC2 you can set `log: false` so that you don't get the error log popping up when you review.
