### ISSUE TITLE
Only hide NEXT clozes

### ISSUE THREAD

**Issue by Cubicle13** [TRIAEIOU/flexible-cloze-2#8]
Since using the built-in overlaping clozes my workflow has been drastically altered. How can I configure the hide all function to only hide the next clozes?

**Comment by triaeiou** [comment]
Hi, I am not sure I understand what you mean, do you mean you want pressing the top bar/shortcut `k` to only toggle the active clozes (the cloze(s) with the ordinal being reviewed) or something else? If so, at the moment there is no such configuration option, but it wouldn't be too hard to create.

Could you give an example of a simple note, something like the following, and what you expect to happen?
```text
Non-nested: {{c1::cloze}}
A: {{c2::nested {{c3::cloze}} here}}
```

**Comment by Cubicle13** [comment]
Non-nested: {{c1::cloze}} {{c2::cloze}} {{c3::cloze}}
When it's cloze 1's turn; hide clozes 2 and 3. 
When it's cloze 2's turn; hide cloze 3
Nested: {{c4::nested {{c5::cloze}} {{c6::cloze}}  here}}
When it's close 5 turn, dont hide close 4, or any clozes it is nested in. However, rules for next non-nested clozes in the same level should still apply; so hide cloze 6.

**Comment by triaeiou** [comment]
Ok, there is no such functionality at the moment, when you write "next cloze" are you referring to cloze ordinal or document order? I.e. which clozes will be hidden when reviewing `c2` in `first {{c3::this}}, then a {{c2::cloze}} and {{c1::another}}`?

**Comment by Cubicle13** [comment]
I believe document order is the most practical implementation; In the example given above, when reviewing c2, c1 should be hidden.

**Comment by triaeiou** [comment]
Check if this is what you're looking for (for the min template): [fc2m-front.html](https://gist.github.com/TRIAEIOU/39e45e5050a816a1f1714d2439f68cca) and [fc2m-back.html](https://gist.github.com/TRIAEIOU/84d2e0009b4ab54d94f180fbe03bfdde)

**Comment by Cubicle13** [comment]
This works fine!

**Comment by triaeiou** [comment]
Configuration option `'preceding'` implemented.
